"""empty message

Revision ID: 15fe2ea317a5
Revises: ad6833d9650f
Create Date: 2019-08-14 14:28:22.587822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fe2ea317a5'
# revision order: ad6833d9650f -> 8aee64a56377 -> 15fe2ea317a5
#   !! should be 8aee64a56377 then no alembic -c migrations/alembic.ini merge heads !!
down_revision = 'ad6833d9650f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
